from lxml import etree

service_draft = r'C:\Users\hjkristenson\PycharmProjects\gis-services\image_services\rtc_services\USDA_RTC_VV_230707_0039.sddraft'
service_draft_out = r'C:\Users\hjkristenson\PycharmProjects\gis-services\image_services\rtc_services\USDA_RTC_VV_test.sddraft'

tree = etree.parse(service_draft)

extensions = tree.find("/Configurations/SVCConfiguration/Definition/Extensions")

xsi_type = etree.QName("http://www.w3.org/2001/XMLSchema-instance", "type")

svc_extension = etree.SubElement(extensions, 'SVCExtension', {xsi_type: 'typens:SVCExtension'})

svc_ext_elements = [('Enabled', '', ''), ('Info', {xsi_type: 'typens:PropertySet'}),
                    ('Props', {xsi_type: 'typens:PropertySet'}), ('TypeName', '', '')]

for sub_el in svc_ext_elements:
    if sub_el[1] == '':
        etree.SubElement(svc_extension, sub_el[0])
    else:
        etree.SubElement(svc_extension, sub_el[0], sub_el[1])
        sub_el_path = tree.find(f"/Configurations/SVCConfiguration/Definition/Extensions/SVCExtension/{sub_el[0]}")
        etree.SubElement(sub_el_path, 'PropertyArray', {xsi_type: 'typens:ArrayOfPropertySetProperty'})

tree.find("/Configurations/SVCConfiguration/Definition/Extensions/SVCExtension/Enabled").text = 'true'

sub_props = tree.find("/Configurations/SVCConfiguration/Definition/Extensions/SVCExtension/Info/PropertyArray")
for el in [('WebEnabled', 'true'),
           ('WebCapabilities', 'GetCapabilities,GetMap,GetFeatureInfo,GetStyles,GetLegendGraphic,GetSchemaExtension')]:
    add_prop = etree.SubElement(sub_props, 'PropertySetProperty', {xsi_type: 'typens:PropertySetProperty'})
    key = etree.SubElement(add_prop, 'Key')
    key.text = el[0]
    value = etree.SubElement(add_prop, 'Value', {xsi_type: 'xs:string'})
    value.text = el[1]

sub_props = tree.find("/Configurations/SVCConfiguration/Definition/Extensions/SVCExtension/Props/PropertyArray")
element_contents = [('name', 'WMS'),
                    ('contactOrganization', 'Alaska Satellite Facility'),
                    ('address', '2156 Koyukuk Drive'),
                    ('addressType', 'physical'),
                    ('city', 'Fairbanks'),
                    ('stateOrProvince', 'Alaska'),
                    ('country', 'US'),
                    ('contactVoiceTelephone', '907-474-5041'),
                    ('contactElectronicMailAddress', 'uso@asf.alaska.edu'),
                    ('accessConstraints',
                     'There are no restrictions on the use of this data, but it must be acknowledged or '
                     'cited as follows: "This imagery was generated by ASF DAAC HyP3 using GAMMA software. '
                     'Contains modified Copernicus Sentinel data, processed by ESA."')
                    ]

for el in element_contents:
    add_prop = etree.SubElement(sub_props, 'PropertySetProperty', {xsi_type: 'typens:PropertySetProperty'})
    key = etree.SubElement(add_prop, 'Key')
    key.text = el[0]
    value = etree.SubElement(add_prop, 'Value', {xsi_type: 'xs:string'})
    value.text = el[1]

for el in ['title', 'abstract']:
    add_prop = etree.SubElement(sub_props, 'PropertySetProperty', {xsi_type: 'typens:PropertySetProperty'})
    key = etree.SubElement(add_prop, 'Key')
    key.text = el
    etree.SubElement(add_prop, 'Value', {xsi_type: 'xs:string'})

tree.find("/Configurations/SVCConfiguration/Definition/Extensions/SVCExtension/TypeName").text = 'WMSServer'

tree.write(service_draft_out)
