name: Add release checklist comment

on:
  pull_request:
    types:
      - opened
    branches:
      - main

jobs:
  add-release-template-comment:
    uses: ASFHyP3/actions/.github/workflows/reusable-release-checklist-comment.yml@v0.18.1
    secrets:
      USER_TOKEN: ${{ secrets.TOOLS_BOT_PAK }}
